use std::io::{BufRead, BufReader, Write};
use std::net::{TcpListener, TcpStream};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

fn read_request_cookie(reader: &mut BufReader<TcpStream>) -> std::io::Result<Option<String>> {
    let mut request_line = String::new();
    if reader.read_line(&mut request_line)? == 0 {
        return Ok(None);
    }
    if request_line.trim().is_empty() {
        return Ok(None);
    }

    let mut cookie_header: Option<String> = None;
    loop {
        let mut line = String::new();
        reader.read_line(&mut line)?;
        let line = line.trim();
        if line.is_empty() {
            break;
        }
        if let Some(val) = line.strip_prefix("Cookie:") {
            cookie_header = Some(val.trim().to_string());
        } else if let Some(val) = line.strip_prefix("cookie:") {
            cookie_header = Some(val.trim().to_string());
        }
    }

    Ok(cookie_header)
}

fn spawn_endpoint(captured: Arc<Mutex<Vec<String>>>) -> u16 {
    let listener = TcpListener::bind("127.0.0.1:0").unwrap();
    let port = listener.local_addr().unwrap().port();
    listener.set_nonblocking(true).unwrap();
    std::thread::spawn(move || {
        for _ in 0..1000 {
            match listener.accept() {
                Ok((stream, _)) => {
                    stream.set_nonblocking(false).unwrap();
                    let captured = Arc::clone(&captured);
                    std::thread::spawn(move || {
                        let mut reader = BufReader::new(stream.try_clone().unwrap());
                        let mut writer = stream;
                        if let Ok(Some(cookie)) = read_request_cookie(&mut reader) {
                            captured.lock().unwrap().push(cookie);
                            let _ = writer.write_all(b"HTTP/1.1 200 OK\r\ncontent-length: 2\r\n\r\nok");
                        }
                    });
                }
                Err(ref e) if e.kind() == std::io::ErrorKind::WouldBlock => {
                    std::thread::sleep(Duration::from_millis(5));
                }
                Err(_) => break,
            }
        }
    });
    port
}

#[test]
fn test_plumbrs_cookies_cli() {
    let captured = Arc::new(Mutex::new(Vec::new()));
    let port = spawn_endpoint(Arc::clone(&captured));

    let temp_dir = std::env::temp_dir();
    let cookie_file = temp_dir.join(format!("cookies_test_{}.txt", std::process::id()));
    let cookie_content = "\
# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n#HttpOnly_127.0.0.1\tFALSE\t/\tFALSE\t2000000000\tRefreshToken\tmock_token_123\n#HttpOnly_127.0.0.1\tFALSE\t/\tFALSE\t2000000000\tBearerToken\tmock_bearer_456\n";
    std::fs::write(&cookie_file, cookie_content).unwrap();

    let bin = env!("CARGO_BIN_EXE_plumbrs");
    let status = std::process::Command::new(bin)
        .args([
            "-t",
            "1",
            "-c",
            "1",
            "-r",
            "1",
            "--cookies",
            cookie_file.to_str().unwrap(),
        ])
        .arg(format!("http://127.0.0.1:{port}/"))
        .status()
        .unwrap();

    assert!(status.success());

    let _ = std::fs::remove_file(cookie_file);

    let start = Instant::now();
    while captured.lock().unwrap().is_empty() && start.elapsed() < Duration::from_secs(5) {
        std::thread::sleep(Duration::from_millis(20));
    }

    let caps = captured.lock().unwrap();
    assert_eq!(caps.len(), 1, "Expected 1 captured request");
    let header = &caps[0];
    assert!(header.contains("RefreshToken=mock_token_123"));
    assert!(header.contains("BearerToken=mock_bearer_456"));
}
